routes/web.php
        Route::impersonate();

        /**
         * Dashboard
         */

        Route::get('/', [
            'as' => 'dashboard',
            'uses' => 'DashboardController@index'
        ]);

        /**
         * User Profile
         */

        Route::get('profile', [
            'as' => 'profile',
            'uses' => 'ProfileController@index'
        ]);

        Route::get('profile/activity', [
            'as' => 'profile.activity',
            'uses' => 'ProfileController@activity'
        ]);

        Route::put('profile/details/update', [
            'as' => 'profile.update.details',
            'uses' => 'ProfileController@updateDetails'
        ]);

        Route::post('profile/avatar/update', [
            'as' => 'profile.update.avatar',
            'uses' => 'ProfileController@updateAvatar'
        ]);

        Route::post('profile/avatar/update/external', [
            'as' => 'profile.update.avatar-external',
            'uses' => 'ProfileController@updateAvatarExternal'
        ]);

        Route::put('profile/login-details/update', [
            'as' => 'profile.update.login-details',
            'uses' => 'ProfileController@updateLoginDetails'
        ]);

        /**
         * Two-Factor Authentication Setup
         */

        if (settings('2fa.enabled')) {
            Route::post('two-factor/enable', [
                'as' => 'two-factor.enable',
                'uses' => 'TwoFactorController@enable'
            ]);

            Route::get('two-factor/verification', [
                'as' => 'two-factor.verification',
                'uses' => 'TwoFactorController@verification',
                'middleware' => 'verify-2fa-phone'
            ]);

            Route::post('two-factor/resend', [
                'as' => 'two-factor.resend',
                'uses' => 'TwoFactorController@resend',
                'middleware' => ['throttle:1,1', 'verify-2fa-phone']
            ]);

            Route::post('two-factor/verify', [
                'as' => 'two-factor.verify',
                'uses' => 'TwoFactorController@verify',
                'middleware' => 'verify-2fa-phone'
            ]);

            Route::post('two-factor/disable', [
                'as' => 'two-factor.disable',
                'uses' => 'TwoFactorController@disable'
            ]);
        }

        /**
         * Sessions
         */

        Route::get('profile/sessions', [
            'as' => 'profile.sessions',
            'uses' => 'ProfileController@sessions'
        ]);

        Route::delete('profile/sessions/{session}/invalidate', [
            'as' => 'profile.sessions.invalidate',
            'uses' => 'ProfileController@invalidateSession'
        ]);

        /**
         * User Management
         */
        Route::get('user', [
            'as' => 'user.list',
            'uses' => 'UsersController@index'
        ]);

        Route::get('user/create', [
            'as' => 'user.create',
            'uses' => 'UsersController@create'
        ]);

        Route::post('user/create', [
            'as' => 'user.store',
            'uses' => 'UsersController@store'
        ]);

        Route::get('user/{user}/show', [
            'as' => 'user.show',
            'uses' => 'UsersController@view'
        ]);

        Route::get('user/{user}/edit', [
            'as' => 'user.edit',
            'uses' => 'UsersController@edit'
        ]);

        Route::put('user/{user}/update/details', [
            'as' => 'user.update.details',
            'uses' => 'UsersController@updateDetails'
        ]);

        Route::put('user/{user}/update/login-details', [
            'as' => 'user.update.login-details',
            'uses' => 'UsersController@updateLoginDetails'
        ]);

        Route::delete('user/{user}/delete', [
            'as' => 'user.delete',
            'uses' => 'UsersController@delete'
        ]);

        Route::post('user/{user}/update/avatar', [
            'as' => 'user.update.avatar',
            'uses' => 'UsersController@updateAvatar'
        ]);

        Route::post('user/{user}/update/avatar/external', [
            'as' => 'user.update.avatar.external',
            'uses' => 'UsersController@updateAvatarExternal'
        ]);

        Route::get('user/{user}/sessions', [
            'as' => 'user.sessions',
            'uses' => 'UsersController@sessions'
        ]);

        Route::delete('user/{user}/sessions/{session}/invalidate', [
            'as' => 'user.sessions.invalidate',
            'uses' => 'UsersController@invalidateSession'
        ]);

        Route::post('user/{user}/two-factor/enable', [
            'as' => 'user.two-factor.enable',
            'uses' => 'UsersController@enableTwoFactorAuth'
        ]);

        Route::post('user/{user}/two-factor/disable', [
            'as' => 'user.two-factor.disable',
            'uses' => 'UsersController@disableTwoFactorAuth'
        ]);

        /**
         * Roles & Permissions
         */

        Route::get('role', [
            'as' => 'role.index',
            'uses' => 'RolesController@index'
        ]);

        Route::get('role/create', [
            'as' => 'role.create',
            'uses' => 'RolesController@create'
        ]);

        Route::post('role/store', [
            'as' => 'role.store',
            'uses' => 'RolesController@store'
        ]);

        Route::get('role/{role}/edit', [
            'as' => 'role.edit',
            'uses' => 'RolesController@edit'
        ]);

        Route::put('role/{role}/update', [
            'as' => 'role.update',
            'uses' => 'RolesController@update'
        ]);

        Route::delete('role/{role}/delete', [
            'as' => 'role.delete',
            'uses' => 'RolesController@delete'
        ]);


        Route::post('permission/save', [
            'as' => 'permission.save',
            'uses' => 'PermissionsController@saveRolePermissions'
        ]);

        Route::resource('permission', 'PermissionsController');

        /**
         * Settings
         */

        Route::get('settings', [
            'as' => 'settings.general',
            'uses' => 'SettingsController@general',
            'middleware' => 'permission:settings.general'
        ]);

        Route::post('settings/general', [
            'as' => 'settings.general.update',
            'uses' => 'SettingsController@update',
            'middleware' => 'permission:settings.general'
        ]);

        Route::get('settings/auth', [
            'as' => 'settings.auth',
            'uses' => 'SettingsController@auth',
            'middleware' => 'permission:settings.auth'
        ]);

        Route::post('settings/auth', [
            'as' => 'settings.auth.update',
            'uses' => 'SettingsController@update',
            'middleware' => 'permission:settings.auth'
        ]);

    // Only allow managing 2FA if AUTHY_KEY is defined inside .env file
        if (env('AUTHY_KEY')) {
            Route::post('settings/auth/2fa/enable', [
                'as' => 'settings.auth.2fa.enable',
                'uses' => 'SettingsController@enableTwoFactor',
                'middleware' => 'permission:settings.auth'
            ]);

            Route::post('settings/auth/2fa/disable', [
                'as' => 'settings.auth.2fa.disable',
                'uses' => 'SettingsController@disableTwoFactor',
                'middleware' => 'permission:settings.auth'
            ]);
        }

        Route::post('settings/auth/registration/captcha/enable', [
            'as' => 'settings.registration.captcha.enable',
            'uses' => 'SettingsController@enableCaptcha',
            'middleware' => 'permission:settings.auth'
        ]);

        Route::post('settings/auth/registration/captcha/disable', [
            'as' => 'settings.registration.captcha.disable',
            'uses' => 'SettingsController@disableCaptcha',
            'middleware' => 'permission:settings.auth'
        ]);

        Route::get('settings/notifications', [
            'as' => 'settings.notifications',
            'uses' => 'SettingsController@notifications',
            'middleware' => 'permission:settings.notifications'
        ]);

        Route::post('settings/notifications', [
            'as' => 'settings.notifications.update',
            'uses' => 'SettingsController@update',
            'middleware' => 'permission:settings.notifications'
        ]);

        /**
         * Activity Log
         */

        Route::get('activity', [
            'as' => 'activity.index',
            'uses' => 'ActivityController@index'
        ]);

        Route::get('activity/user/{user}/log', [
            'as' => 'activity.user',
            'uses' => 'ActivityController@userActivity'
        ]);

    });


    /**
     * Installation
     */

    $router->get('install', [
        'as' => 'install.start',
        'uses' => 'InstallController@index'
    ]);

    $router->get('install/requirements', [
        'as' => 'install.requirements',
        'uses' => 'InstallController@requirements'
    ]);

    $router->get('install/permissions', [
        'as' => 'install.permissions',
        'uses' => 'InstallController@permissions'
    ]);

    $router->get('install/database', [
        'as' => 'install.database',
        'uses' => 'InstallController@databaseInfo'
    ]);

    $router->get('install/start-installation', [
        'as' => 'install.installation',
        'uses' => 'InstallController@installation'
    ]);

    $router->post('install/start-installation', [
        'as' => 'install.installation',
        'uses' => 'InstallController@installation'
    ]);

    $router->post('install/install-app', [
        'as' => 'install.install',
        'uses' => 'InstallController@install'
    ]);

    $router->get('install/complete', [
        'as' => 'install.complete',
        'uses' => 'InstallController@complete'
    ]);

    $router->get('install/error', [
        'as' => 'install.error',

app/Permission.php
<?php

namespace Vanguard;

use Illuminate\Database\Eloquent\Model;

class Permission extends Model
{
    protected $table = 'permissions';

    protected $fillable = ['name', 'display_name', 'description'];

    protected $casts = [
        'removable' => 'boolean'
    ];
}

app/Http/Controllers/Api/Authorization/PermissionsController.php
<?php

namespace Vanguard\Http\Controllers\Api\Authorization;

use Vanguard\Http\Controllers\Api\ApiController;
use Vanguard\Http\Requests\Permission\CreatePermissionRequest;
use Vanguard\Http\Requests\Permission\RemovePermissionRequest;
use Vanguard\Http\Requests\Permission\UpdatePermissionRequest;
use Vanguard\Permission;
use Vanguard\Repositories\Permission\PermissionRepository;
use Vanguard\Transformers\PermissionTransformer;

/**
 * Class PermissionsController
 * @package Vanguard\Http\Controllers\Api\Users
 */
class PermissionsController extends ApiController
{
    /**
     * @var PermissionRepository
     */
    private $permissions;

    public function __construct(PermissionRepository $permissions)
    {
        $this->permissions = $permissions;
        $this->middleware('auth');
        $this->middleware('permission:permissions.manage');
    }

    /**
     * Get all system permissions.
     * @return \Illuminate\Http\JsonResponse
     */
    public function index()
    {
        return $this->respondWithCollection(
            $this->permissions->all(),
            new PermissionTransformer
        );
    }

    /**
     * Create new permission from request.
     * @param CreatePermissionRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(CreatePermissionRequest $request)
    {
        $permission = $this->permissions->create(
            $request->only(['name', 'display_name', 'description'])
        );

        return $this->respondWithItem($permission, new PermissionTransformer);
    }

    /**
     * Get info about specified permission.
     * @param Permission $permission
     * @return \Illuminate\Http\JsonResponse
     */
    public function show(Permission $permission)
    {
        return $this->respondWithItem($permission, new PermissionTransformer);
    }

    /**
     * Update specified permission.
     * @param Permission $permission
     * @param UpdatePermissionRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(Permission $permission, UpdatePermissionRequest $request)
    {
        $input = collect($request->all());

        $permission = $this->permissions->update(
            $permission->id,
            $input->only(['name', 'display_name', 'description'])->toArray()
        );

        return $this->respondWithItem($permission, new PermissionTransformer);
    }

    /**
     * Remove specified permission from storage.
     * @param Permission $permission
     * @param RemovePermissionRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy(Permission $permission, RemovePermissionRequest $request)
    {
        $this->permissions->delete($permission->id);

        return $this->respondWithSuccess();
    }
}

app/Http/Controllers/Web/PermissionsController.php
<?php

namespace Vanguard\Http\Controllers\Web;

use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Vanguard\Events\Role\PermissionsUpdated;
use Vanguard\Http\Controllers\Controller;
use Vanguard\Http\Requests\Permission\CreatePermissionRequest;
use Vanguard\Http\Requests\Permission\UpdatePermissionRequest;
use Vanguard\Permission;
use Vanguard\Repositories\Permission\PermissionRepository;
use Vanguard\Repositories\Role\RoleRepository;
use Illuminate\Http\Request;

/**
 * Class PermissionsController
 * @package Vanguard\Http\Controllers
 */
class PermissionsController extends Controller
{
    /**
     * @var RoleRepository
     */
    private $roles;
    /**
     * @var PermissionRepository
     */
    private $permissions;

    /**
     * PermissionsController constructor.
     * @param RoleRepository $roles
     * @param PermissionRepository $permissions
     */
    public function __construct(RoleRepository $roles, PermissionRepository $permissions)
    {
        $this->middleware('auth');
        $this->middleware('permission:permissions.manage');
        $this->roles = $roles;
        $this->permissions = $permissions;
    }

    /**
     * Displays the page with all available permissions.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $roles = $this->roles->all();
        $permissions = $this->permissions->all();

        return view('permission.index', compact('roles', 'permissions'));
    }

    /**
     * Displays the form for creating new permission.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $edit = false;

        return view('permission.add-edit', compact('edit'));
    }

    /**
     * Store permission to database.
     *
     * @param CreatePermissionRequest $request
     * @return mixed
     */
    public function store(CreatePermissionRequest $request)
    {
        $this->permissions->create($request->all());

        return redirect()->route('permission.index')
            ->withSuccess(trans('app.permission_created_successfully'));
    }

    /**
     * Displays the form for editing specific permission.
     *
     * @param Permission $permission
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Permission $permission)
    {
        $edit = true;

        return view('permission.add-edit', compact('edit', 'permission'));
    }

    /**
     * Update specified permission.
     *
     * @param Permission $permission
     * @param UpdatePermissionRequest $request
     * @return mixed
     */
    public function update(Permission $permission, UpdatePermissionRequest $request)
    {
        $this->permissions->update($permission->id, $request->all());

        return redirect()->route('permission.index')
            ->withSuccess(trans('app.permission_updated_successfully'));
    }

    /**
     * Destroy the permission if it is removable.
     *
     * @param Permission $permission
     * @return mixed
     * @throws \Exception
     */
    public function destroy(Permission $permission)
    {
        if (! $permission->removable) {
            throw new NotFoundHttpException;
        }

        $this->permissions->delete($permission->id);

        return redirect()->route('permission.index')
            ->withSuccess(trans('app.permission_deleted_successfully'));
    }

    /**
     * Update permissions for each role.
     *
     * @param Request $request
     * @return mixed
     */
    public function saveRolePermissions(Request $request)
    {
        $roles = $request->get('roles');

        $allRoles = $this->roles->lists('id');

        foreach ($allRoles as $roleId) {
            $permissions = array_get($roles, $roleId, []);
            $this->roles->updatePermissions($roleId, $permissions);
        }

        event(new PermissionsUpdated);

        return redirect()->route('permission.index')
            ->withSuccess(trans('app.permissions_saved_successfully'));
    }
}

resources/views/permission/add-edit.blade.php
@extends('layouts.app')

@section('page-title', trans('app.permissions'))
@section('page-heading', $edit ? $permission->name : trans('app.create_new_permission'))

@section('breadcrumbs')
    <li class="breadcrumb-item">
        <a href="{{ route('permission.index') }}">@lang('app.permissions')</a>
    </li>
    <li class="breadcrumb-item active">
        {{ $edit ? trans('app.edit') : trans('app.create') }}
    </li>
@stop

@section('content')

@include('partials.messages')

@if ($edit)
    {!! Form::open(['route' => ['permission.update', $permission->id], 'method' => 'PUT', 'id' => 'permission-form']) !!}
@else
    {!! Form::open(['route' => 'permission.store', 'id' => 'permission-form']) !!}
@endif

<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-3">
                <h5 class="card-title">
                    @lang('app.permission_details')
                </h5>
                <p class="text-muted font-weight-light">
                    A general permission information.
                </p>
            </div>
            <div class="col-md-9">
                <div class="form-group">
                    <label for="name">@lang('app.name')</label>
                    <input type="text" class="form-control" id="name"
                           name="name" placeholder="@lang('app.permission_name')" value="{{ $edit ? $permission->name : old('name') }}">
                </div>
                <div class="form-group">
                    <label for="display_name">@lang('app.display_name')</label>
                    <input type="text" class="form-control" id="display_name"
                           name="display_name" placeholder="@lang('app.display_name')" value="{{ $edit ? $permission->display_name : old('display_name') }}">
                </div>
                <div class="form-group">
                    <label for="description">@lang('app.description')</label>
                    <textarea name="description" id="description" class="form-control">{{ $edit ? $permission->description : old('description') }}</textarea>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-2">
        <button type="submit" class="btn btn-primary">
            {{ $edit ? trans('app.update_permission') : trans('app.create_permission') }}
        </button>
    </div>
</div>

@stop

@section('scripts')
    @if ($edit)
        {!! JsValidator::formRequest('Vanguard\Http\Requests\Permission\UpdatePermissionRequest', '#permission-form') !!}
    @else
        {!! JsValidator::formRequest('Vanguard\Http\Requests\Permission\CreatePermissionRequest', '#permission-form') !!}
    @endif
@stop

resources/views/permission/index.blade.php
@extends('layouts.app')

@section('page-title', trans('app.permissions'))
@section('page-heading', trans('app.permissions'))

@section ('breadcrumbs')
    <li class="breadcrumb-item active">
        @lang('app.permissions')
    </li>
@stop

@section('content')

@include('partials.messages')

{!! Form::open(['route' => 'permission.save', 'class' => 'mb-4']) !!}

<div class="card">
    <div class="card-body">

        <div class="row mb-3 pb-3 border-bottom-light">
            <div class="col-lg-12">
                <div class="float-right">
                    <a href="{{ route('permission.create') }}" class="btn btn-primary btn-rounded">
                        <i class="fas fa-plus mr-2"></i>
                        @lang('app.add_permission')
                    </a>
                </div>
            </div>
        </div>

        <div class="table-responsive" id="users-table-wrapper">
            <table class="table table-striped table-borderless">
                <thead>
                    <tr>
                        <th class="min-width-200">@lang('app.name')</th>
                        @foreach ($roles as $role)
                            <th class="text-center">{{ $role->display_name }}</th>
                        @endforeach
                        <th class="text-center min-width-100">@lang('app.action')</th>
                    </tr>
                </thead>
                <tbody>
                @if (count($permissions))
                    @foreach ($permissions as $permission)
                        <tr>
                            <td>{{ $permission->display_name ?: $permission->name }}</td>

                            @foreach ($roles as $role)
                                <td class="text-center">
                                    <div class="custom-control custom-checkbox">
                                        {!!
                                            Form::checkbox(
                                                "roles[{$role->id}][]",
                                                $permission->id,
                                                $role->hasPermission($permission->name),
                                                [
                                                    'class' => 'custom-control-input',
                                                    'id' => "cb-{$role->id}-{$permission->id}"
                                                ]
                                            )
                                        !!}
                                        <label class="custom-control-label d-inline"
                                               for="cb-{{ $role->id }}-{{ $permission->id }}"></label>
                                    </div>
                                </td>
                            @endforeach

                            <td class="text-center">
                                <a href="{{ route('permission.edit', $permission->id) }}" class="btn btn-icon"
                                   title="@lang('app.edit_permission')" data-toggle="tooltip" data-placement="top">
                                    <i class="fas fa-edit"></i>
                                </a>

                                @if ($permission->removable)
                                    <a href="{{ route('permission.destroy', $permission->id) }}" class="btn btn-icon"
                                       title="@lang('app.delete_permission')"
                                       data-toggle="tooltip"
                                       data-placement="top"
                                       data-method="DELETE"
                                       data-confirm-title="@lang('app.please_confirm')"
                                       data-confirm-text="@lang('app.are_you_sure_delete_permission')"
                                       data-confirm-delete="@lang('app.yes_delete_it')">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="4"><em>@lang('app.no_records_found')</em></td>
                    </tr>
                @endif
                </tbody>
            </table>
        </div>
    </div>
</div>

@if (count($permissions))
    <div class="row">
        <div class="col-md-2">
            <button type="submit" class="btn btn-primary">@lang('app.save_permissions')</button>
        </div>
    </div>
@endif

{!! Form::close() !!}

@stop